---
driver:
  name: ec2

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
 # require_chef_omnibus: 22.2.807
  data_bags_path: ../../data_bags/
  client_rb:
    chef_license: accept

verifier:
  name: inspec

platforms:
  - name: ubuntu-20.04

suites:
  - name: default
    run_list:
      - recipe[lamp::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
    driver:
